[package]
name = "raid_night"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.4.0"
macroquad = "0.3.16"
rusqlite = "0.27.0"
